version: '3'
services:
 mongodb:
  image: "mongo"
  environment:
    MONGO_INITDB_DATABASE: contact_db
  ports:
  - "27017:27017"
 backend:
  build: ./ContactListBackend/
  ports:
   - "3030:3030"
  volumes:
   - ./ContactListBackend:/usr/src/app
  depends_on:
   - mongodb
# app:
#  build: ./ContactListFrontend/
#  command: "npm start"
#  ports:
#   - "4200:4200"
#  expose:
#   - "4200"
##  volumes:
##   - ./ContactListFrontend:/usr/app/
#  depends_on:
#   - backend
